AdministracionDeLaboratorios.InterfazGrafica/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using AdministracionDeLaboratorios.LogicaDeNegocio;
using AdministracionDeLaboratorios.AccesoADatos;
using AdministracionDeLaboratorios.InterfazGrafica;
namespace AdministracionDeLaboratorios.InterfazGrafica.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente

        AlumnosBL AlumBL = new AlumnosBL();
        CarrerasBL CarreBL = new CarrerasBL();
        DiasBL DiaBL = new DiasBL();
        DocentesBL DocentBL = new DocentesBL();
        HorariosBL HorarBL = new HorariosBL();
        LaboratoriosBL LaborBL = new LaboratoriosBL();
        UsuariosBL UsuBL = new UsuariosBL();


        public ActionResult Informacion()
        {
            return View();
        }

        #region Docente

        public ActionResult ListadoDocente()
        {
            List<DOCENTE> lista = DocentBL.obtenerDocente();
            return View(lista);
        }

        public ActionResult VerDetalleDocente(int pId)
        {
            var docente = DocentBL.obtenerDocentePorId(pId);
            return View(docente);
        }

        #endregion

        #region Carrera
        public ActionResult ListadoCarrera()
        {
            List<CARRERA> lista = CarreBL.obtenerCarrera();
            return View(lista);
        }
        public ActionResult VerDetalleCarrera(int pId)
        {
            var carrera = CarreBL.obtenerCarreraPorId(pId);
            return View(carrera);
        }
        #endregion

        #region Laboratorio

        public ActionResult ListadoLaboratorio()
        {
            List<LABORATORIO> lista = LaborBL.obtenerLaboratorio();
            return View(lista);
        }

        public ActionResult VerDetalleLaboratorio(int pId)
        {
            var laboratorio = LaborBL.obtenerLaboratorioPorId(pId);
            return View(laboratorio);
        }

        #endregion
    }
}

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/Informacion.cshtml
@{
    ViewBag.Title = "Informacion";
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto</title>
    <meta charset="UTF-8">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/estilo.css" rel="stylesheet" />


</head>
<body >
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>
    </header>
    

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/ListadoCarrera.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.CARRERA>
@{
    ViewBag.Title = "ListadoCarrera";
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto</title>
    <meta charset="UTF-8">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/estilo.css" rel="stylesheet" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>
    </header>

    <section id="cajas2">
        <div class="contenedor">


            <div class="d-flex justify-content-center">
                <div class="card" style="width: 100rem;">
                    <table class="table table-striped table-condensed">
                        <h2 class="d-flex justify-content-center">Listado Carrera</h2>
                        <thead>
                            <tr>
                                <td>
                                    Id
                                </td>
                                <th>
                                    Nombre
                                </th>
                                <th>
                                    Docente
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdCarrera)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DOCENTE.Nombre)
                                    </td>

                                    <td>
                                        <a class="btn btn-success" data-id="@item.IdCarrera" href="@Url.Action("VerDetalleCarrera", "Cliente", new { pId = item.IdCarrera})">Ver detalle</a>
                                   
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/ListadoDocente.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.DOCENTE>
@{
    ViewBag.Title = "ListadoDocente";
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto</title>
    <meta charset="UTF-8">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/estilo.css" rel="stylesheet" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>
    </header>
    
    <section id="cajas2">
        <div class="contenedor">

            
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 100rem;">
                    <table class="table table-striped table-condensed">
                        <h2 class="d-flex justify-content-center">Listado Docente</h2>
                        <thead>
                            <tr>
                                <td>
                                    Id
                                </td>
                                <th>
                                    Nombre
                                </th>
                                <th>
                                    Apellido
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdDocente)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Apellido)
                                    </td>
                                    <td>
                                        <a class="btn btn-success" data-id="@item.IdDocente" href="@Url.Action("VerDetalleDocente", "Cliente", new { pId = item.IdDocente })">Detalle</a>

                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/ListadoLaboratorio.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.LABORATORIO>
@{
    ViewBag.Title = "ListadoLaboratorio";
    Layout = null;
}


<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto</title>
    <meta charset="UTF-8">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/estilo.css" rel="stylesheet" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>
    </header>

    <section id="cajas2">
        <div class="contenedor">

            <div class="d-flex justify-content-center">
                <div class="card" style="width: 100rem;">
                    <table class="table table-striped table-condensed">
                        <h2 class="d-flex justify-content-center">Listado De Laboratorios</h2>
                        <thead>
                            <tr>
                                <th>
                                    Nombre
                                </th>
                                <th>
                                    Numero
                                </th>

                                <th>
                                    Ubicacion
                                </th>
                                <th>
                                    Estado
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Numero)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ubicacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CARRERA.Nombre)
                                </td>
                                <td>
                                    <a class="btn btn-success" data-id="@item.IdLaboratorio" href="@Url.Action("VerDetalleLaboratorio", "Cliente", new { pId = item.IdLaboratorio})">Ver detalle</a>

                                </td>

                                <td></td>

                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/VerDetalleCarrera.cshtml
@{
    ViewBag.Title = "VerDetalleCarrera";
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>

    @*<meta charset="UTF-8">
        <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/estilo.css" rel="stylesheet" />*@

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>

    </header>


   
    <div class="d-flex justify-content-center">
        <div class="card" style="width: 50rem;">
            <h2 class="d-flex justify-content-center"> Detalle de La Carrera</h2>
            <div class="d-flex justify-content-center">
                <div class="card" style="width: 20rem;">

                    <div class="form-group">
                        <label>Carrera:</label>
                        <small>@Model.Nombre</small>
                    </div>
                    <div class="form-group">
                        <label>Catedratico:</label>
                        <small>@Model.DOCENTE.Nombre @Model.DOCENTE.Apellido</small>
                    </div>
                    <a class="btn btn-success" href="@Url.Action("ListadoCarrera", "Cliente")">Inico</a>

                </div>
            </div>
        </div>
    </div>

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/VerDetalleDocente.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.DOCENTE
@{
    ViewBag.Title = "VerDetalleDocente";
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
  
    @*<meta charset="UTF-8">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/estilo.css" rel="stylesheet" />*@

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>

    </header>
    <h2 class="d-flex justify-content-center">Detalle de Docente</h2>
    <div class="d-flex justify-content-center">
        <div class="card" style="width: 20rem;">
            <img src="~/Fotos/@Model.Foto" style="width:205px; height:200px;" class="img-thumbnail img-responsive" alt="Imagen" />
            <div class="card-body">
                <h5 class="card-title">Docente:   <small>@Model.Nombre @Model.Apellido</small></h5>
                <a class="btn btn-success" href="@Url.Action("ListadoDocente", "Cliente")">Inico</a>
             
            </div>
        </div>
    </div>

</body>
</html>

AdministracionDeLaboratorios.InterfazGrafica/Views/Cliente/VerDetalleLaboratorio.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.LABORATORIO
@{
    ViewBag.Title = "VerDetalleLaboratorio";
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>

    @*<meta charset="UTF-8">
        <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/estilo.css" rel="stylesheet" />*@

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--definimos la ruta principal de la aplicacion-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="~/Content/estilo.css" rel="stylesheet" />
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="margin: 0px;padding-top: 0px;">
    <header class="menu-fixed" style="border-left-style: solid;border-left-width: 0px;padding-top: 1px;padding-bottom: 0px;border-bottom-width: 20px;padding-right: 0px;padding-left: 10px;">
        <div class="contenedor">

            <h3><span class="resaltado">ADMINISTRACION DE LABORATORIOS</span></h3>
            <a class="btn btn-secondary" href="@Url.Action("Informacion", "Cliente")">
                Inicio
                <span class="glyphicon glyphicon-home "></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("LogInAlumno", "LogIn")">
                Cerrar Sesión
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoDocente", "Cliente")">
                Docente
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoCarrera", "Cliente")">
                Carrera
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
            <a class="btn btn-secondary" href="@Url.Action("ListadoLaboratorio", "Cliente")">
                Laboratorios
                <span class="glyphicon glyphicon-log-out"></span>
            </a>
        </div>

    </header>
    <h2 class="d-flex justify-content-center">Detalle del Laboratorio</h2>
    <div class="d-flex justify-content-center">
        <div class="card" style="width: 20rem;">
            <img src="~/Fotos/@Model.Foto" style="width:205px; height:200px;" class="img-thumbnail img-responsive" alt="Imagen" />
            <div class="card-body">
                <h5 class="card-title">Laboratorio:   <small>@Model.Nombre</small></h5>
                <div>
                    <label>Numero:</label>
                    <small>@Model.Numero</small>
                </div>
                <div>
                    <label>Ubicacion:</label>
                    <small>@Model.Ubicacion</small>
                </div>
                <div>
                    <label>Estado:</label>
                    <small>@Model.CARRERA.Nombre</small>
                </div>
            </div>
            <a class="btn btn-success" href="@Url.Action("ListadoLaboratorio", "Cliente")">Inico</a>

        </div>
    </div>

</body>
</html>