AdministracionDeLaboratorios.InterfazGrafica/Controllers/AdministradorController.cs
using AdministracionDeLaboratorios.AccesoADatos;
using AdministracionDeLaboratorios.LogicaDeNegocio;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AdministracionDeLaboratorios.InterfazGrafica.Controllers
{
    public class AdministradorController : Controller
    {
        // GET: Administrador

        AlumnosBL AlumBL = new AlumnosBL();
        CarrerasBL CarreBL = new CarrerasBL();
        DiasBL DiaBL = new DiasBL();
        DocentesBL DocentBL = new DocentesBL();
        HorariosBL HorarBL = new HorariosBL();
        LaboratoriosBL LaborBL = new LaboratoriosBL();
        UsuariosBL UsuBL = new UsuariosBL();
       
        #region ALUMNO
        public ActionResult ListadoAlumnos()
        {
            List<ALUMNO> lista = AlumBL.obtenerAlumno();
            return View(lista);
        }

        public ActionResult AgregarAlumno()
        {

            List<CARRERA> listaCarrera = CarreBL.obtenerCarrera();
            ViewBag.Carrera = listaCarrera;

            List<HORARIO> listarHorario = HorarBL.obtenerOrario();
            ViewBag.Horario = listarHorario;

            return View();
        }

        [HttpPost]

        public ActionResult AgregarAlumno(ALUMNO pAlumno, int pCarrera, int pHorario)
        {
            ALUMNO _al = pAlumno;

            _al.HORARIO = HorarBL.obtenerHorarioPorId(pHorario);
            _al.CARRERA = CarreBL.obtenerCarreraPorId(pCarrera);
            if (pAlumno.Archivo != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(pAlumno.Archivo.FileName);
                string extension = Path.GetExtension(pAlumno.Archivo.FileName);
                fileName = fileName + extension;
                pAlumno.Foto = fileName;
                fileName = Path.Combine(Server.MapPath("~/Fotos/"), fileName);
                pAlumno.Archivo.SaveAs(fileName);
            }

            if (AlumBL.agregarAlumno(_al) > 0)
            {
      
                return RedirectToAction("ListadoAlumnos");
            }
            else
            {
                return View();
            }
        }
        public ActionResult VerDetalleAlumno(int pId)
        {
            var alumno = AlumBL.obtenerAlumnoPorId(pId);
            return View(alumno);
        }

        public ActionResult ModificarAlumno(int pId)
        {
            List<CARRERA> listaCarrera = CarreBL.obtenerCarrera();
            ViewBag.Carrera = listaCarrera;

            List<HORARIO> listarHorario = HorarBL.obtenerOrario();
            ViewBag.Horario = listarHorario;

            var alumnos = AlumBL.obtenerAlumnoPorId(pId);
            return View(alumnos);
        }

        [HttpPost]
        public ActionResult ModificarAlumno(ALUMNO pAlumno, int pHorario, int pCarrera )
        {
            ALUMNO _al = pAlumno;

            _al.HORARIO = HorarBL.obtenerHorarioPorId(pHorario);
            _al.CARRERA = CarreBL.obtenerCarreraPorId(pCarrera);
            if (pAlumno.Archivo != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(pAlumno.Archivo.FileName);
                string extension = Path.GetExtension(pAlumno.Archivo.FileName);
                fileName = fileName + extension;
                pAlumno.Foto = fileName;
                fileName = Path.Combine(Server.MapPath("~/Fotos/"), fileName);
                pAlumno.Archivo.SaveAs(fileName);
            }

            if (AlumBL.modificarAlumno(_al) > 0)
            {

                return RedirectToAction("ListadoAlumnos");
            }
            else
            {
                return View();
            }
        }
        public ActionResult EliminarAlumno(int pId)
        {
            List<CARRERA> listaCarrera = CarreBL.obtenerCarrera();
            ViewBag.Carrera = listaCarrera;

            List<HORARIO> listarHorario = HorarBL.obtenerOrario();
            ViewBag.Horario = listarHorario;

            var alumnos = AlumBL.obtenerAlumnoPorId(pId);
            return View(alumnos);
        }

        [HttpPost]
        public ActionResult EliminarAlumno(ALUMNO pAlumno)
        {
            ALUMNO _alumn = pAlumno;

            if (AlumBL.eliminarAlumno(pAlumno) > 0)
            {
                return RedirectToAction("ListadoAlumnos");
            }

            else
            {
                return View(pAlumno);
            }

        }
        #endregion

        #region DOCENTE
        public ActionResult ListadoDocente()
        {
            List<DOCENTE> lista = DocentBL.obtenerDocente();
            return View(lista);
        }
        
        public ActionResult AgregarDocente()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgregarDocente(DOCENTE pDocente)
        {
           
            DOCENTE _Doc = pDocente;
            
            if (pDocente.Archivo != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(pDocente.Archivo.FileName);
                string extension = Path.GetExtension(pDocente.Archivo.FileName);
                fileName = fileName + extension;
                pDocente.Foto = fileName;
                fileName = Path.Combine(Server.MapPath("~/Fotos/"), fileName);
                pDocente.Archivo.SaveAs(fileName);
            }

            if (DocentBL.agregarDocente(_Doc) > 0)
            {
                return RedirectToAction("ListadoDocente");
            }
            else
            {
                return View();
            }
        }

        public ActionResult VerDetalleDocente(int pId)
        {
            var docente = DocentBL.obtenerDocentePorId(pId);
            return View(docente);
        }

        public ActionResult ModificarDocente(int pId)
        {

            var docente = DocentBL.obtenerDocentePorId(pId);
            return View(docente);
        }

        [HttpPost]
        public ActionResult ModificarDocente(DOCENTE pDocente)
        {
            DOCENTE _Doc = pDocente;
            
            if (pDocente.Archivo != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(pDocente.Archivo.FileName);
                string extension = Path.GetExtension(pDocente.Archivo.FileName);
                fileName = fileName + extension;
                pDocente.Foto = fileName;
                fileName = Path.Combine(Server.MapPath("~/Fotos/"), fileName);
                pDocente.Archivo.SaveAs(fileName);
            }

            if (DocentBL.modificarDocente(_Doc) > 0)
            {

                return RedirectToAction("ListadoDocente");
            }
            else
            {
                return View();
            }
        }

        public ActionResult EliminarDocente(int pId)
        {
            List<DOCENTE> listaDocente = DocentBL.obtenerDocente();
            ViewBag.Docente = listaDocente;

            

            var docente = DocentBL.obtenerDocentePorId(pId);
            return View(docente);
        }

        [HttpPost]
        public ActionResult EliminarDocente(DOCENTE pDocente)
        {
            DOCENTE _docent = pDocente;

            if (DocentBL.eliminarDocente(pDocente) > 0)
            {
                return RedirectToAction("ListadoDocente");
            }

            else
            {
                return View(pDocente);
            }

        }
        #endregion

        #region DIAS
        public ActionResult ListadoDias()
        {
            List<DIA> lista = DiaBL.obtenerDia();
            return View(lista);
        }

        public ActionResult AgregarDia()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgregarDia(DIA pDia)
        {

            DIA _Dia = pDia;
            
            if (DiaBL.agregarDia(_Dia) > 0)
            {
                return RedirectToAction("ListadoDias");
            }
            else
            {
                return View();
            }
        }

        public ActionResult VerDetalleDia(int pId)
        {
            var dia = DiaBL.obtenerDiaPorId(pId);
            return View(dia);
        }
        
        public ActionResult ModificarDia(int pId)
        {

            var dia = DiaBL.obtenerDiaPorId(pId);
            return View(dia);
        }

        [HttpPost]
        public ActionResult ModificarDia(DIA pDia)
        {
            DIA _Dia = pDia;

            
            if (DiaBL.modificarDia(_Dia) > 0)
            {

                return RedirectToAction("ListadoDias");
            }
            else
            {
                return View();
            }
        }

        public ActionResult EliminarDia(int pId)
        {
            List<DIA> listaDia = DiaBL.obtenerDia();
            ViewBag.Dia = listaDia;

            var dia = DiaBL.obtenerDiaPorId(pId);
            return View(dia);
        }

        [HttpPost]
        public ActionResult EliminarDia(DIA pDia)
        {
            DIA _dia = pDia;

            if (DiaBL.eliminarDia(pDia) > 0)
            {
                return RedirectToAction("ListadoDias");
            }

            else
            {
                return View(pDia);
            }

        }
        
        #endregion

        #region CARRERA
        public ActionResult ListadoCarrera()
        {
            List<CARRERA> lista = CarreBL.obtenerCarrera();
            return View(lista);
        }

        public ActionResult AgregarCarrera()
        {
            List<DOCENTE> listarDocente = DocentBL.obtenerDocente();
            ViewBag.Docente = listarDocente;

            return View();
        }

        [HttpPost]
        public ActionResult AgregarCarrera(CARRERA pCarrera, int pDocente)
        {
            CARRERA _Carre = pCarrera;

            _Carre.DOCENTE = DocentBL.obtenerDocentePorId(pDocente);

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/AgregarCarrera.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.CARRERA

@{

    ViewBag.Title = "Agregar Carrera";

    var listarDocente = ViewBag.Docente;

}

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("AgregarCarrera", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div id="contenedor">

        <div id="der">
            <div class="form-group">
                <label>Carrera</label>
                <input type="text" name="Nombre" class="form-control" required />
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Docente</label>
                <select name="pDocente" class="form-control">

                    @foreach (var p in listarDocente)
                    {
                        <option value="@p.IdDocente">@p.Nombre @p.Apellido</option>
                    }
                </select>
            </div>

            <div class="form-group col-sm-offset-0">
                <input type="submit" value="Agregar" style="margin-top: 5px;" class="btn btn-block btn-success" />
            </div>
        </div>
    </div>

}

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/AgregarDia.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.DIA

@{

    ViewBag.Title = "Agregar Dia";

    //var listaDia = ViewBag.Dia;

}

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("AgregarDia", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div id="contenedor">

        <div id="izq">
            <div class="form-group">
                <h3>Dia</h3>
            </div>
        </div>
        <div id="der">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="Nombre" class="form-control" required />
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>

            @*<div class="form-group">
                <label>Dias</label>
                <select name="pCarrera" class="form-control">

                    @foreach (var p in listaDia)
                    {
                        <option value="@p.IdDia">@p.Nombre</option>
                    }
                </select>
            </div>*@

            <div class="form-group col-sm-offset-0">
                <input type="submit" value="Agregar Dia" style="margin-top: 5px;" class="btn btn-block btn-success" />
            </div>
        </div>
    </div>

}

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/EliminarDocente.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.DOCENTE

@{

    ViewBag.Title = "Eliminar Docente";

    var listaDocente = ViewBag.Docente;

}

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("EliminarDocente", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdDocente)
    <div id="contenedor">
        <div class="d-flex justify-content-center">
            <h2>Datos del Docente</h2>
        </div>
        <div id="izq">
            <div class="form-group">
                <img src="~/Fotos/@Model.Foto" style="width:205%;" class="img-thumbnail img-responsive" id="imagePreview" />
                <input type="file" name="Archivo" accept="image/jpeg, image/png" class="form-control" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))">
            </div>

        </div>
        <div id="der">

            <div>
                <div class="form-group">
                    <label>Nombres</label>
                    <input type="text" name="Nombre" class="form-control" required value="@Model.Nombre" />
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Apellidos</label>
                    <input type="text" name="Apellido" class="form-control" required value="@Model.Apellido" />
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-offset-0">
                    <input type="submit" value="Eliminar" style="margin-top: 5px;" class="btn btn-block btn-success" />
                </div>
            </div>

        </div>
    </div>

}
<script>
    function ShowImagePreview(imageUploader, previewImage) {
        if (imageUploader.files && imageUploader.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(previewImage).attr('src', e.target.result);
            }
            reader.readAsDataURL(imageUploader.files[0]);
        }
    }
    function toUpper(control) {

        if (/[a-z]/.test(control.value)) {
            control.value = control.value.toUpperCase();
        }
    }

</script>

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/EliminarUsuario.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.USUARIO
@{
    ViewBag.Title = "EliminarUsuario";

    var listaUsuario = ViewBag.Usuario;
}

<h2>EliminarUsuario</h2>

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("EliminarUsuario", "Administrador", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdUsuario)
    <div id="contenedor">
        <div class="d-flex justify-content-center">
            <h2>Dia</h2>
        </div>

        <div id="der">

            <div>
                <div class="form-group">
                    <label>Usuario</label>
                    <input type="text" name="Nombre" class="form-control" required value="@Model.Nombre" />
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label>Contraseña</label>
                    <input type="text" name="Password" class="form-control" required value="@Model.Password" />
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-offset-0">
                    <input type="submit" value="Eliminar" style="margin-top: 5px;" class="btn btn-block btn-success" />
                </div>
            </div>

        </div>
    </div>

}

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/ListadoAlumnos.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.ALUMNO>
@{
    ViewBag.Title = "ListadoAlumnos";
}

<h2>Listado Alumnos</h2>
<a class="btn btn-success" href="@Url.Action("AgregarAlumno", "Administrador")">Agregar Alumno</a>

<section id="cajas2">
    <div class="contenedor">

        <table class="table table-striped table-condensed">

            <thead>
                <tr>
                    <td>
                        Id
                    </td>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Apellido
                    </th>
                    <th>
                        Numero de carnet
                    </th>
                    <th>
                        Edad
                    </th>
                    <th>
                        fecha de Ingreso
                    </th>
                    <th>
                        Direccion
                    </th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdAlumno)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumCarnet)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Edad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaIngreso)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Direccion)
                        </td>

                        <td>
                            <a class="btn btn-success" data-id="@item.IdAlumno" href="@Url.Action("VerDetalleAlumno", "Administrador", new { pId = item.IdAlumno})">Ver detalle</a>
                            <a class="btn btn-success" data-id="@item.IdAlumno" href="@Url.Action("ModificarAlumno", "Administrador" , new { pId = item.IdAlumno})">Editar</a>
                            <a class="btn btn-success" data-id="@item.IdAlumno" href="@Url.Action("EliminarAlumno", "Administrador", new { pId = item.IdAlumno})">Eliminar</a>
                        </td>

                        <td></td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/ListadoCarrera.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.CARRERA>
@{
    ViewBag.Title = "ListadoCarrera";
}

<h2>Listado de Carrera</h2>
<a class="btn btn-success" href="@Url.Action("AgregarCarrera", "Administrador")">Agregar Carrera</a>

<section id="cajas2">
    <div class="contenedor">

        <table class="table table-striped table-condensed">

            <thead>
                <tr>
                    <td>
                        Id
                    </td>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Docente
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdCarrera)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DOCENTE.Nombre)
                        </td>

                        <td>
                            <a class="btn btn-success" data-id="@item.IdCarrera" href="@Url.Action("VerDetalleCarrera", "Administrador", new { pId = item.IdCarrera})">Ver detalle</a>
                            <a class="btn btn-success" data-id="@item.IdCarrera" href="@Url.Action("ModificarCarrera", "Administrador" , new { pId = item.IdCarrera})">Editar</a>
                         
                        </td>

                        <td></td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/ListadoUsuario.cshtml
@model IEnumerable<AdministracionDeLaboratorios.AccesoADatos.USUARIO>
@{
    ViewBag.Title = "ListadoUsuario";
}

<h2>Listado de Usuario</h2>
<a class="btn btn-success" href="@Url.Action("AgregarUsuario", "Administrador")">Agregar Usuario</a>

<section id="cajas2">
    <div class="contenedor">

        <table class="table table-striped table-condensed">

            <thead>
                <tr>
                    <td>
                        Id
                    </td>
                    <th>
                        Usuario
                    </th>
                    <th>
                        Contraseña
                    </th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdUsuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>
                        <a class="btn btn-success" data-id="@item.IdUsuario" href="@Url.Action("ModificarUsuario", "Administrador", new { pId = item.IdUsuario })">Editar</a>
                        <a class="btn btn-success" data-id="@item.IdUsuario" href="@Url.Action("EliminarUsuario", "Administrador", new { pId = item.IdUsuario })">Eliminar</a>
                    </td>

                    <td></td>

                </tr>
                }
            </tbody>
        </table>
    </div>
</section>

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/ModificarAlumno.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.ALUMNO

@{

    ViewBag.Title = "Modificar Alumno";

    var listaCarrera = ViewBag.Carrera;
    var listaHorario = ViewBag.Horario;

}

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("ModificarAlumno", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdAlumno)
<div id="contenedor">
    <div class="d-flex justify-content-center">
        <h2>Datos del Alumno</h2>
    </div>
    <div id="izq">
        <div class="form-group">
            <img src="~/Fotos/@Model.Foto" style="width:205%;" class="img-thumbnail img-responsive" id="imagePreview" />
            <input type="file" name="Archivo" accept="image/jpeg, image/png" class="form-control" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))">
        </div>

    </div>
    <div id="der">
        
        <div>
            <div class="form-group">
                <label>Nombres</label>
                <input type="text" name="Nombre" class="form-control" required value="@Model.Nombre" />
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Apellidos</label>
                <input type="text" name="Apellido" class="form-control" required value="@Model.Apellido" />
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Carnet Nº</label>
                <input type="text" name="NumCarnet" class="form-control" required value="@Model.NumCarnet" />
                @Html.ValidationMessageFor(model => model.NumCarnet, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Edad</label>
                <input type="text" name="Edad" class="form-control" required value="@Model.Edad" />
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Fecha de Ingreso</label>
                <input type="datetime" name="FechaIngreso" class="form-control" required value="@Model.FechaIngreso" />
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Horario</label>
                <select name="pHorario" class="form-control">
                    @foreach (var m in listaHorario)
                    {
                        if (m.IdHorario == Model.HORARIO.IdHorario)
                        {
                            <option value="@m.IdHorario" selected="selected">@m.Turno</option>
                        }
                        else
                        {
                            <option value="@m.IdHorario">@m.Turno</option>
                        }


                    }
                </select>
            </div>
            <div class="form-group">
                <label>Direccion</label>
                <input type="text" name="Direccion" class="form-control" required value="@Model.Direccion" />
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Carrera</label>
                <select name="pCarrera" class="form-control">
                    @foreach (var m in listaCarrera)
                    {
                        if (m.IdCarrera == Model.CARRERA.IdCarrera)
                        {
                            <option value="@m.IdCarrera" selected="selected">@m.Nombre</option>
                        }
                        else
                        {
                            <option value="@m.IdCarrera">@m.Nombre</option>
                        }


                    }
                </select>
            </div>
            <div class="form-group col-sm-offset-0">
                <input type="submit" value="Modificar" style="margin-top: 5px;" class="btn btn-block btn-success" />
            </div>
        </div>
       
    </div>
</div>

}
<script>
    function ShowImagePreview(imageUploader, previewImage) {
        if (imageUploader.files && imageUploader.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(previewImage).attr('src', e.target.result);
            }
            reader.readAsDataURL(imageUploader.files[0]);
        }
    } https://www.youtube.com/watch?v=1-DZa9m6zws
    function toUpper(control) {

        if (/[a-z]/.test(control.value)) {
            control.value = control.value.toUpperCase();
        }
    }

</script>

AdministracionDeLaboratorios.InterfazGrafica/Views/Administrador/ModificarDocente.cshtml
@model AdministracionDeLaboratorios.AccesoADatos.DOCENTE

@{

    ViewBag.Title = "Modificar Docente";

    var listaCarrera = ViewBag.Carrera;
    var listaHorario = ViewBag.Horario;

}

<style>
    .input {
        font-family: 'Lucida Sans';
        font-size: 12px;
        text-transform: uppercase;
    }
</style>

@using (Html.BeginForm("ModificarDocente", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdDocente)
    <div id="contenedor">
        <div class="d-flex justify-content-center">
            <h2>Datos del Docente</h2>
        </div>
        <div id="izq">
            <div class="form-group">
                <img src="~/Fotos/@Model.Foto" style="width:205%;" class="img-thumbnail img-responsive" id="imagePreview" />
                <input type="file" name="Archivo" accept="image/jpeg, image/png" class="form-control" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))">
            </div>
    
        </div>
        <div id="der">

            <div>
                <div class="form-group">
                    <label>Nombres</label>
                    <input type="text" name="Nombre" class="form-control" required value="@Model.Nombre" />
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label>Apellidos</label>
                    <input type="text" name="Apellido" class="form-control" required value="@Model.Apellido" />
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-offset-0">
                    <input type="submit" value="Modificar" style="margin-top: 5px;" class="btn btn-block btn-success" />
                </div>
            </div>

        </div>
    </div>

}
<script>
    function ShowImagePreview(imageUploader, previewImage) {
        if (imageUploader.files && imageUploader.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(previewImage).attr('src', e.target.result);
            }
            reader.readAsDataURL(imageUploader.files[0]);
        }
    }
    function toUpper(control) {

        if (/[a-z]/.test(control.value)) {
            control.value = control.value.toUpperCase();
        }
    }

</script>